language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -qr requirements.txt
  - pip install -q sphinx sphinx_rtd_theme
  - python setup.py install

# command to run tests
script:
  - pytest tinder/
  - cd docs && make html && touch _build/html/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $gh
  keep_history: false
  local_dir: docs/_build/html
  verbose: true
  on:
    branch: master
