language: python
python:
  - "3.7"
dist: xenial
# command to install dependencies
install:
  - pip install -qr requirements.txt
  - pip install -q sphinx sphinx_rtd_theme
  - python setup.py install
  - pip install pytest-cov
  - pip install coveralls

# command to run tests
script:
  - pytest --cov=tinder/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $gh
  keep_history: false
  local_dir: docs/_build/html
  verbose: true
  on:
    branch: master

after_success:
  - coveralls
  - cd docs && make html && touch _build/html/.nojekyll
